# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad046fed0c3dc67b747c22cbddc21aba3df25b193d0dec3aacc45732436b7c2dcff6ef812cf75106e67f4826e5a44b36837657e38cb842c1066d63ee41b5aed0

test:
  secret_key_base: 4b8d4c62e192313a8841794e1dcc633027aeb7bb012a1234d96d9f1c5f5519c4594fba596320d85e85082c393886ee6f0c4eb12f5dca489ad7a5c27b62b1c35a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
